name: rrc
channels:
  - defaults
dependencies:
  - python=3.6.9
  - numpy==1.19.1
    #- pinocchio==2.4.7
  - pip==20.1.1
  - pytorch
  - cudatoolkit=10.2
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - pybullet==2.8.4
    - gym==0.17.2
    - opencv-python==4.2.0.34
    - catkin-pkg==0.4.22
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - hydra-core
    - pandas
    - ipdb
    - tqdm
    - torchvision
    - yapf
    - sklearn
    - matplotlib
    - kornia
