# env
use_old_simulator: false
difficulty: 1
env: task${difficulty}
action_type: position # torque or both
action_repeat: 1
episode_length: 500
num_corners: 1
action_scale: 1.0
# domain randomization
randomize: False
obj_pos_noise_std: 0.001
time_step_low: 0.001
time_step_high: 0.02
cube_mass_low: 0.17
cube_mass_high: 0.23
gravity_low: -9.85
gravity_high: -9.77
restitution_low: 0.75
restitution_high: 0.85
max_velocity_low: 9.5
max_velocity_high: 10.5
lateral_friction_low: 0.08
lateral_friction_high: 0.12
camera_rate_fps_low: 2
camera_rate_fps_high: 5

excluded_obses: null #desired_goal_orientation:achieved_goal_orientation
use_pretrained: false
pretrained_model_dir: /private/home/denisy/workspace/research/rrc/pretrained_agents/phase1
# teacher
use_teacher: false
teacher_model_dir: /private/home/denisy/workspace/research/rrc/exp/2020.11.05/120800_ddpg_task14_old_rew_rnd/0/model
teacher_model_step: 4200000
teacher_init_p: 1.0
teacher_max_step: 3000000
teacher_excluded_obses: action
# denis curriculum
train_initializer: random
eval_initializer: random
curriculum_max_step: 1000000
curriculum_init_p: 0.0
# train
num_train_steps: 1000000
num_seed_steps: 1000
num_train_iters: 1
replay_buffer_capacity: ${num_train_steps}
seed: 1
# eval
eval_frequency: 10000
num_eval_episodes: 10
# misc
log_frequency_step: 10000
log_save_tb: true
save_video: true
save_train_video: false
video_fps: 10
device: cuda
# saving
save_frequency: 10000
# global params
lr: 1e-4
batch_size: 128
parameterization: clipped
actor_stddev: 0.2
hidden_depth: 2
hidden_dim: 1024
nstep: 5
random_nstep: true



agent:
  name: ddpg
  class: ddpg.DDPGAgent
  params:
    obs_shape: ??? # to be specified later
    obs_slices: ??? # to be specified later
    action_shape: ??? # to be specified later
    action_range: ??? # to be specified later
    device: ${device}
    critic_cfg: ${critic}
    actor_cfg: ${actor}
    discount: 0.99
    lr: ${lr}
    actor_update_frequency: 1
    critic_tau: 0.01
    critic_target_update_frequency: 1
    batch_size: ${batch_size}
    nstep: ${nstep}
    use_ln: true
    excluded_obses: ${excluded_obses}

critic:
  class: ddpg.Critic
  params:
    obs_shape: ???
    action_shape: ${agent.params.action_shape}
    hidden_dim: ${hidden_dim}
    hidden_depth: ${hidden_depth}
    use_ln: ${agent.params.use_ln}

actor:
  class: ddpg.Actor
  params:
    obs_shape: ???
    action_shape: ${agent.params.action_shape}
    hidden_dim: ${hidden_dim}
    hidden_depth: ${hidden_depth}
    stddev: ${actor_stddev}
    parameterization: ${parameterization}
    use_ln: ${agent.params.use_ln}
    
experiment: bench

# hydra configuration
hydra:
  name: ${env}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    params:
      queue_parameters:
        slurm:
          max_num_timeout: 100000
          time: 4319
          #partition: learnfair
          partition: priority
          comment: iclr_deadline_sep_22
    mem_limit: 64
